[project]
name = "renderhive-api"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "django~=5.2",
    "django-environ~=0.14",
    "djangorestframework~=3.17",
    "psycopg[binary]~=3.3",
    "django-cors-headers~=4.9",
    "django-redis~=7.0",
    "redis~=8.0",
    "gunicorn~=26.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar~=7.0",
    "django-extensions~=4.1",
    "factory-boy>=3.3.3",
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
    "ruff~=0.15",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.per-file-ignores]
"config/settings/*.py" = ["F403", "F405"]
"**/migrations/*.py" = ["E501"]
