# Generated by Django 5.2.16 on 2026-07-15 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workernode",
            name="last_ping",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
