# Generated by Django 5.2.16 on 2026-07-19 15:33

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workernode_last_ping'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'worker pool',
                'verbose_name_plural': 'worker pools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workernode',
            name='cores',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workernode',
            name='gpu_models',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='workernode',
            name='memory_mb',
            field=models.PositiveIntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='workernode',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='workernode',
            name='system_info',
            field=models.JSONField(blank=True, default=dict, help_text='Transient and live utilization metrics.'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.workerpool'),
        ),
    ]
