# Generated by Django 5.2.16 on 2026-08-14 16:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_task_last_score_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('actor_username', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'farm event',
                'verbose_name_plural': 'farm events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='telemetry_f_event_t_bac9b3_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='telemetry_f_target__d73931_idx'), models.Index(fields=['severity', '-created_at'], name='telemetry_f_severit_79c835_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_hostname', models.CharField(db_index=True, max_length=255)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_used_mb', models.PositiveIntegerField(default=0)),
                ('memory_total_mb', models.PositiveIntegerField(default=4096)),
                ('vram_percent', models.FloatField(default=0.0)),
                ('active_tasks', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'worker metric snapshot',
                'verbose_name_plural': 'worker metric snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['worker_hostname', '-recorded_at'], name='telemetry_w_worker__ad1029_idx'), models.Index(fields=['-recorded_at'], name='telemetry_w_recorde_7e62a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispatchTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_hostname', models.CharField(db_index=True, max_length=255)),
                ('candidate_count', models.IntegerField(default=1)),
                ('ai_invoked', models.BooleanField(db_index=True, default=False)),
                ('ai_latency_ms', models.FloatField(blank=True, null=True)),
                ('ai_reason', models.TextField(blank=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_traces', to='jobs.job')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_traces', to='jobs.task')),
            ],
            options={
                'verbose_name': 'dispatch trace',
                'verbose_name_plural': 'dispatch traces',
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['job', '-dispatched_at'], name='telemetry_d_job_id_169160_idx'), models.Index(fields=['worker_hostname', '-dispatched_at'], name='telemetry_d_worker__360746_idx'), models.Index(fields=['ai_invoked', '-dispatched_at'], name='telemetry_d_ai_invo_f0d137_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('worker_hostname', models.CharField(db_index=True, max_length=255)),
                ('exit_status', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('peak_memory_mb', models.PositiveIntegerField(default=0)),
                ('output_image_path', models.CharField(blank=True, max_length=2048)),
                ('error_tail', models.TextField(blank=True, help_text='Fast-access failure excerpt.')),
                ('log_output', models.TextField(blank=True, help_text='Full stdout/stderr text, TOAST-compressed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(help_text='Denormalized Job foreign key for fast cascading and filtering.', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='jobs.job')),
                ('task', models.ForeignKey(help_text='The task this log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='jobs.task')),
            ],
            options={
                'verbose_name': 'task execution log',
                'verbose_name_plural': 'task execution logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-attempt_number'], name='telemetry_t_task_id_e21118_idx'), models.Index(fields=['job', '-created_at'], name='telemetry_t_job_id_c81d2d_idx'), models.Index(fields=['worker_hostname', '-created_at'], name='telemetry_t_worker__39948b_idx')],
            },
        ),
    ]
