# Generated by Django 5.2.16 on 2026-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmevent',
            name='target_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
