# Generated by Django 5.2.16 on 2026-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_farmevent_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionlog',
            name='ai_explanation',
            field=models.TextField(blank=True, help_text='Pre-computed AI explanation of the error.'),
        ),
    ]
