# Generated by Django 5.2.17 on 2026-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_taskexecutionlog_ai_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionlog',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskexecutionlog',
            name='peak_cpu_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
