/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/frames/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing frames and handling Worker state transition actions.
         *
         *     List/retrieve endpoints are nested under a layer:
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/``
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/``
         *
         *     State transition action endpoints are on the top-level ``/api/frames/``
         *     router, identified by UUID only (no nesting required for Workers):
         *         ``POST /api/frames/{id}/start/``
         *         ``POST /api/frames/{id}/succeed/``
         *         ``POST /api/frames/{id}/fail/``
         *         ``POST /api/frames/{id}/skip/``
         *         ``POST /api/frames/{id}/checkpoint/``
         */
        get: operations["frames_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing frames and handling Worker state transition actions.
         *
         *     List/retrieve endpoints are nested under a layer:
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/``
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/``
         *
         *     State transition action endpoints are on the top-level ``/api/frames/``
         *     router, identified by UUID only (no nesting required for Workers):
         *         ``POST /api/frames/{id}/start/``
         *         ``POST /api/frames/{id}/succeed/``
         *         ``POST /api/frames/{id}/fail/``
         *         ``POST /api/frames/{id}/skip/``
         *         ``POST /api/frames/{id}/checkpoint/``
         */
        get: operations["frames_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/checkpoint/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Increment the checkpoint counter for a frame in progress.
         *
         *     Called by a Worker when it saves a resume checkpoint (e.g. a V-Ray
         *     ``.vrimg`` file). The frame transitions to ``CHECKPOINT`` state to
         *     indicate that progress has been persisted.
         *
         *     Args:
         *         request: HTTP request.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` with the new checkpoint count.
         *         ``409 Conflict`` if the frame is not in RUNNING or CHECKPOINT state.
         */
        post: operations["frames_checkpoint_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/fail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as FAILED or retry it based on the retry budget.
         *
         *     Increments the retry counter. If ``retries >= max_retries``, the frame
         *     transitions to ``FAILED`` permanently. Otherwise it reverts to ``READY``
         *     for re-dispatch.
         *
         *     Args:
         *         request: HTTP request containing ``exit_status``.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` with the resulting state (``failed`` or ``retrying``).
         *         ``409 Conflict`` if the frame is not in RUNNING or CHECKPOINT state.
         */
        post: operations["frames_fail_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/skip/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Dismiss a failed frame, allowing its dependents to proceed.
         *
         *     Only available to staff users. Sets the frame state to ``SKIPPED``,
         *     which (via signals) satisfies any dependencies blocked on this frame.
         *
         *     Args:
         *         request: HTTP request.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` on success.
         *         ``403 Forbidden`` if the requesting user is not staff.
         *         ``409 Conflict`` if the frame is not in FAILED state.
         */
        post: operations["frames_skip_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as RUNNING when a Worker begins execution.
         *
         *     Records the Worker hostname and execution start timestamp. Only
         *     valid when the frame is in ``READY`` state.
         *
         *     Args:
         *         request: HTTP request containing ``worker_name``.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` on success.
         *         ``409 Conflict`` if the frame is not in READY state.
         */
        post: operations["frames_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/succeed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as SUCCEEDED and record telemetry.
         *
         *     Transitions state, logs exit code and stop timestamp.
         *     Returns 409 if the frame isn't currently running/checkpointing.
         */
        post: operations["frames_succeed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/dispatch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically find, lock, and dispatch a READY frame to a worker. */
        post: operations["frames_dispatch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing, submitting, updating, and deleting jobs.
         *
         *     Endpoints:
         *         ``GET    /api/jobs/``         ù list all jobs, supports filtering.
         *         ``POST   /api/jobs/``         ù submit a new job with nested layers.
         *         ``GET    /api/jobs/{id}/``    ù retrieve full job detail with layers.
         *         ``PATCH  /api/jobs/{id}/``    ù update priority or visible_name.
         *         ``DELETE /api/jobs/{id}/``    ù delete a job and all its layers/frames.
         *         ``POST   /api/jobs/{id}/pause/``  ù pause the job.
         *         ``POST   /api/jobs/{id}/resume/`` ù resume a paused job.
         */
        get: operations["jobs_list"];
        put?: never;
        /**
         * @description ViewSet for listing, submitting, updating, and deleting jobs.
         *
         *     Endpoints:
         *         ``GET    /api/jobs/``         ù list all jobs, supports filtering.
         *         ``POST   /api/jobs/``         ù submit a new job with nested layers.
         *         ``GET    /api/jobs/{id}/``    ù retrieve full job detail with layers.
         *         ``PATCH  /api/jobs/{id}/``    ù update priority or visible_name.
         *         ``DELETE /api/jobs/{id}/``    ù delete a job and all its layers/frames.
         *         ``POST   /api/jobs/{id}/pause/``  ù pause the job.
         *         ``POST   /api/jobs/{id}/resume/`` ù resume a paused job.
         */
        post: operations["jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only ViewSet for listing and retrieving layers scoped to a job.
         *
         *     Endpoints (nested under /api/jobs/{job_pk}/):
         *         ``GET  /api/jobs/{job_pk}/layers/``         ù list all layers for a job.
         *         ``GET  /api/jobs/{job_pk}/layers/{id}/``    ù retrieve a single layer.
         *
         *     All endpoints require authentication. Layers are scoped to the parent job
         *     via the ``job_pk`` URL kwarg.
         */
        get: operations["jobs_layers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing frames and handling Worker state transition actions.
         *
         *     List/retrieve endpoints are nested under a layer:
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/``
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/``
         *
         *     State transition action endpoints are on the top-level ``/api/frames/``
         *     router, identified by UUID only (no nesting required for Workers):
         *         ``POST /api/frames/{id}/start/``
         *         ``POST /api/frames/{id}/succeed/``
         *         ``POST /api/frames/{id}/fail/``
         *         ``POST /api/frames/{id}/skip/``
         *         ``POST /api/frames/{id}/checkpoint/``
         */
        get: operations["jobs_layers_frames_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing frames and handling Worker state transition actions.
         *
         *     List/retrieve endpoints are nested under a layer:
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/``
         *         ``GET  /api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/``
         *
         *     State transition action endpoints are on the top-level ``/api/frames/``
         *     router, identified by UUID only (no nesting required for Workers):
         *         ``POST /api/frames/{id}/start/``
         *         ``POST /api/frames/{id}/succeed/``
         *         ``POST /api/frames/{id}/fail/``
         *         ``POST /api/frames/{id}/skip/``
         *         ``POST /api/frames/{id}/checkpoint/``
         */
        get: operations["jobs_layers_frames_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/checkpoint/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Increment the checkpoint counter for a frame in progress.
         *
         *     Called by a Worker when it saves a resume checkpoint (e.g. a V-Ray
         *     ``.vrimg`` file). The frame transitions to ``CHECKPOINT`` state to
         *     indicate that progress has been persisted.
         *
         *     Args:
         *         request: HTTP request.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` with the new checkpoint count.
         *         ``409 Conflict`` if the frame is not in RUNNING or CHECKPOINT state.
         */
        post: operations["jobs_layers_frames_checkpoint_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/fail/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as FAILED or retry it based on the retry budget.
         *
         *     Increments the retry counter. If ``retries >= max_retries``, the frame
         *     transitions to ``FAILED`` permanently. Otherwise it reverts to ``READY``
         *     for re-dispatch.
         *
         *     Args:
         *         request: HTTP request containing ``exit_status``.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` with the resulting state (``failed`` or ``retrying``).
         *         ``409 Conflict`` if the frame is not in RUNNING or CHECKPOINT state.
         */
        post: operations["jobs_layers_frames_fail_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/skip/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Dismiss a failed frame, allowing its dependents to proceed.
         *
         *     Only available to staff users. Sets the frame state to ``SKIPPED``,
         *     which (via signals) satisfies any dependencies blocked on this frame.
         *
         *     Args:
         *         request: HTTP request.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` on success.
         *         ``403 Forbidden`` if the requesting user is not staff.
         *         ``409 Conflict`` if the frame is not in FAILED state.
         */
        post: operations["jobs_layers_frames_skip_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as RUNNING when a Worker begins execution.
         *
         *     Records the Worker hostname and execution start timestamp. Only
         *     valid when the frame is in ``READY`` state.
         *
         *     Args:
         *         request: HTTP request containing ``worker_name``.
         *         pk: Frame UUID.
         *
         *     Returns:
         *         ``200 OK`` on success.
         *         ``409 Conflict`` if the frame is not in READY state.
         */
        post: operations["jobs_layers_frames_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{layer_pk}/frames/{id}/succeed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark a frame as SUCCEEDED and record telemetry.
         *
         *     Transitions state, logs exit code and stop timestamp.
         *     Returns 409 if the frame isn't currently running/checkpointing.
         */
        post: operations["jobs_layers_frames_succeed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_pk}/layers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only ViewSet for listing and retrieving layers scoped to a job.
         *
         *     Endpoints (nested under /api/jobs/{job_pk}/):
         *         ``GET  /api/jobs/{job_pk}/layers/``         ù list all layers for a job.
         *         ``GET  /api/jobs/{job_pk}/layers/{id}/``    ù retrieve a single layer.
         *
         *     All endpoints require authentication. Layers are scoped to the parent job
         *     via the ``job_pk`` URL kwarg.
         */
        get: operations["jobs_layers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ViewSet for listing, submitting, updating, and deleting jobs.
         *
         *     Endpoints:
         *         ``GET    /api/jobs/``         ù list all jobs, supports filtering.
         *         ``POST   /api/jobs/``         ù submit a new job with nested layers.
         *         ``GET    /api/jobs/{id}/``    ù retrieve full job detail with layers.
         *         ``PATCH  /api/jobs/{id}/``    ù update priority or visible_name.
         *         ``DELETE /api/jobs/{id}/``    ù delete a job and all its layers/frames.
         *         ``POST   /api/jobs/{id}/pause/``  ù pause the job.
         *         ``POST   /api/jobs/{id}/resume/`` ù resume a paused job.
         */
        get: operations["jobs_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description ViewSet for listing, submitting, updating, and deleting jobs.
         *
         *     Endpoints:
         *         ``GET    /api/jobs/``         ù list all jobs, supports filtering.
         *         ``POST   /api/jobs/``         ù submit a new job with nested layers.
         *         ``GET    /api/jobs/{id}/``    ù retrieve full job detail with layers.
         *         ``PATCH  /api/jobs/{id}/``    ù update priority or visible_name.
         *         ``DELETE /api/jobs/{id}/``    ù delete a job and all its layers/frames.
         *         ``POST   /api/jobs/{id}/pause/``  ù pause the job.
         *         ``POST   /api/jobs/{id}/resume/`` ù resume a paused job.
         */
        delete: operations["jobs_destroy"];
        options?: never;
        head?: never;
        /**
         * @description ViewSet for listing, submitting, updating, and deleting jobs.
         *
         *     Endpoints:
         *         ``GET    /api/jobs/``         ù list all jobs, supports filtering.
         *         ``POST   /api/jobs/``         ù submit a new job with nested layers.
         *         ``GET    /api/jobs/{id}/``    ù retrieve full job detail with layers.
         *         ``PATCH  /api/jobs/{id}/``    ù update priority or visible_name.
         *         ``DELETE /api/jobs/{id}/``    ù delete a job and all its layers/frames.
         *         ``POST   /api/jobs/{id}/pause/``  ù pause the job.
         *         ``POST   /api/jobs/{id}/resume/`` ù resume a paused job.
         */
        patch: operations["jobs_partial_update"];
        trace?: never;
    };
    "/api/jobs/{id}/pause/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Pause a job, preventing new frames from being dispatched.
         *
         *     Sets ``is_paused=True`` on the job. Does not terminate currently
         *     running frames ù they will complete their current render.
         *
         *     Args:
         *         request: The HTTP request.
         *         pk: The Job UUID.
         *
         *     Returns:
         *         A ``200 OK`` response with the updated job state.
         */
        post: operations["jobs_pause_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/resume/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Resume a paused job, allowing frames to be dispatched again.
         *
         *     Sets ``is_paused=False`` on the job.
         *
         *     Args:
         *         request: The HTTP request.
         *         pk: The Job UUID.
         *
         *     Returns:
         *         A ``200 OK`` response with the updated job state.
         */
        post: operations["jobs_resume_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for listing, creating, and managing worker pools. */
        get: operations["pools_list"];
        put?: never;
        /** @description ViewSet for listing, creating, and managing worker pools. */
        post: operations["pools_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pools/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for listing, creating, and managing worker pools. */
        get: operations["pools_retrieve"];
        /** @description ViewSet for listing, creating, and managing worker pools. */
        put: operations["pools_update"];
        post?: never;
        /** @description ViewSet for listing, creating, and managing worker pools. */
        delete: operations["pools_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet for listing, creating, and managing worker pools. */
        patch: operations["pools_partial_update"];
        trace?: never;
    };
    "/api/workers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for listing workers and handling heartbeat pings. */
        get: operations["workers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet for listing workers and handling heartbeat pings. */
        get: operations["workers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workers/ping/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register or update a worker's heartbeat. */
        post: operations["workers_ping_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Full read-only frame representation for detail and Worker poll views.
         *
         *     Extends :class:`FrameListSerializer` with execution telemetry fields.
         *
         *     Attributes:
         *         max_memory_used_mb: Peak RSS memory in MB.
         *         cores_used: CPU cores reserved at dispatch time.
         *         checkpoint_count: Number of resume checkpoints saved.
         *         dispatch_order: Dispatch priority within the layer.
         */
        FrameDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly number: number;
            readonly state: components["schemas"]["State23dEnum"];
            /** Dependency count */
            readonly depend_count: number;
            readonly retries: number;
            /** Worker hostname */
            readonly worker_name: string | null;
            /** @description Raw process exit code returned by the worker. -1 means the frame has not completed. */
            readonly exit_status: number;
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly stopped_at: string | null;
            /** Peak memory used (MB) */
            readonly max_memory_used_mb: number;
            readonly cores_used: number | null;
            /** @description How many times the worker has reported saving intermediate progress (useful for resuming aborted frames). */
            readonly checkpoint_count: number;
            /** @description Scheduler priority within the layer. Lower numbers are dispatched first. */
            readonly dispatch_order: number;
        };
        /**
         * @description Validates payload when a Worker reports a frame as FAILED.
         *
         *     Attributes:
         *         exit_status: Non-zero process exit code.
         */
        FrameFail: {
            /** @description Non-zero process exit code from the render process. */
            exit_status: number;
        };
        /**
         * @description Slim read-only frame representation for list views.
         *
         *     Attributes:
         *         id: UUID primary key.
         *         name: Display name (e.g. 'beauty_0042').
         *         number: Render frame index.
         *         state: Current execution state.
         *         depend_count: Number of unresolved dependencies.
         *         retries: Execution attempt count.
         *         worker_name: Hostname of the executing Worker.
         *         exit_status: Process exit code (-1 if not yet run).
         *         started_at: Execution start timestamp.
         *         stopped_at: Execution stop timestamp.
         */
        FrameList: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly number: number;
            readonly state: components["schemas"]["State23dEnum"];
            /** Dependency count */
            readonly depend_count: number;
            readonly retries: number;
            /** Worker hostname */
            readonly worker_name: string | null;
            /** @description Raw process exit code returned by the worker. -1 means the frame has not completed. */
            readonly exit_status: number;
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly stopped_at: string | null;
        };
        /**
         * @description Validates payload when a Worker marks a frame as RUNNING.
         *
         *     Attributes:
         *         worker_name: Hostname of the Worker claiming this frame.
         */
        FrameStart: {
            /** @description Hostname of the Worker claiming this frame. */
            worker_name: string;
        };
        /**
         * @description Validates payload when a Worker reports a frame as SUCCEEDED.
         *
         *     Attributes:
         *         exit_status: Process exit code (should be 0).
         *         max_memory_used_mb: Peak RSS memory in MB.
         *         cores_used: Actual CPU cores used.
         */
        FrameSucceed: {
            /**
             * @description Process exit code. Should be 0 on success.
             * @default 0
             */
            exit_status: number;
            /**
             * @description Peak RSS memory used by the render process, in MB.
             * @default 0
             */
            max_memory_used_mb: number;
            /** @description Actual CPU cores reserved by the Worker at dispatch time. */
            cores_used?: number | null;
        };
        /**
         * @description Write-only serializer for job submission.
         *
         *     Accepts a nested ``layers`` array. The ``name`` field is auto-generated
         *     by the service layer if not provided. The ``submitted_by`` field is
         *     populated from the authenticated session user if available.
         *
         *     Attributes:
         *         layers: Nested list of layer data (required, at least one).
         *         visible_name: Human-readable label for the job.
         *         project: Active show or production segment.
         *         department: Department name.
         *         user: Submitter's display name.
         *         priority: Dispatch priority (1-100).
         *         log_directory: Absolute path for frame logs.
         *         max_frames_per_worker: Concurrent frames per Worker limit.
         */
        JobCreate: {
            visible_name?: string;
            project: string;
            department?: string;
            /** @description The submitter's display name. Defaults to the OS username in the DCC plugin but is manually editable. Matches Deadline's UserName field. */
            user: string;
            priority?: number;
            log_directory: string;
            /**
             * Max concurrent frames per worker
             * @description Limits how many frames from this job a single machine can run at once. Used to prevent a single job from monopolizing nodes with high core counts.
             */
            max_frames_per_worker?: number;
            /** @description If specified, only workers in these pools can process this job. */
            included_pools?: string[];
            /** @description If specified, workers in these pools are strictly prevented from processing this job. */
            excluded_pools?: string[];
            layers: components["schemas"]["LayerCreate"][];
        };
        /**
         * @description Full read-only job representation for detail views.
         *
         *     Extends :class:`JobListSerializer` with nested layers, log directory,
         *     worker concurrency limit, and stop timestamp.
         *
         *     Attributes:
         *         layers: Nested list of all layers belonging to this job.
         *         log_directory: Absolute path for frame logs.
         *         max_frames_per_worker: Concurrent frames per Worker limit.
         *         stopped_at: Timestamp when job reached FINISHED or FAILED.
         */
        JobDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly visible_name: string;
            readonly project: string;
            readonly department: string;
            /** @description The submitter's display name. Defaults to the OS username in the DCC plugin but is manually editable. Matches Deadline's UserName field. */
            readonly user: string;
            readonly state: components["schemas"]["State1dfEnum"];
            readonly priority: number;
            readonly is_paused: boolean;
            readonly total_frames: number;
            readonly waiting_frames: number;
            readonly ready_frames: number;
            readonly running_frames: number;
            readonly succeeded_frames: number;
            readonly failed_frames: number;
            readonly skipped_frames: number;
            readonly depend_frames: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description If specified, only workers in these pools can process this job. */
            readonly included_pools: string[];
            /** @description If specified, workers in these pools are strictly prevented from processing this job. */
            readonly excluded_pools: string[];
            readonly layers: components["schemas"]["LayerDetail"][];
            readonly log_directory: string;
            /**
             * Max concurrent frames per worker
             * @description Limits how many frames from this job a single machine can run at once. Used to prevent a single job from monopolizing nodes with high core counts.
             */
            readonly max_frames_per_worker: number;
            /** Format: date-time */
            readonly stopped_at: string | null;
        };
        /**
         * @description Slim read-only job representation for list views.
         *
         *     Attributes:
         *         id: UUID primary key.
         *         name: System-generated stable identifier.
         *         visible_name: Human-readable label.
         *         project: Active show or production segment.
         *         department: Department name.
         *         user: Submitter's display name.
         *         state: Current execution state.
         *         priority: Dispatch priority (1-100).
         *         is_paused: Standalone pause flag.
         *         total_frames: Counter cache.
         *         waiting_frames: Counter cache.
         *         ready_frames: Counter cache.
         *         running_frames: Counter cache.
         *         succeeded_frames: Counter cache.
         *         failed_frames: Counter cache.
         *         skipped_frames: Counter cache.
         *         depend_frames: Counter cache.
         *         created_at: Submission timestamp.
         *         updated_at: Last update timestamp.
         */
        JobList: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly visible_name: string;
            readonly project: string;
            readonly department: string;
            /** @description The submitter's display name. Defaults to the OS username in the DCC plugin but is manually editable. Matches Deadline's UserName field. */
            readonly user: string;
            readonly state: components["schemas"]["State1dfEnum"];
            readonly priority: number;
            readonly is_paused: boolean;
            readonly total_frames: number;
            readonly waiting_frames: number;
            readonly ready_frames: number;
            readonly running_frames: number;
            readonly succeeded_frames: number;
            readonly failed_frames: number;
            readonly skipped_frames: number;
            readonly depend_frames: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description If specified, only workers in these pools can process this job. */
            readonly included_pools: string[];
            /** @description If specified, workers in these pools are strictly prevented from processing this job. */
            readonly excluded_pools: string[];
        };
        /**
         * @description Write-only serializer for partial job updates.
         *
         *     Only exposes fields that are safe to mutate post-submission. State
         *     transitions (pause, resume) use dedicated action endpoints instead.
         *
         *     Attributes:
         *         visible_name: Human-readable label.
         *         priority: Dispatch priority (1-100).
         *         max_frames_per_worker: Concurrent frames per Worker limit.
         */
        JobPatch: {
            visible_name?: string;
            priority?: number;
            /**
             * Max concurrent frames per worker
             * @description Limits how many frames from this job a single machine can run at once. Used to prevent a single job from monopolizing nodes with high core counts.
             */
            max_frames_per_worker?: number;
            /** @description If specified, only workers in these pools can process this job. */
            included_pools?: string[];
            /** @description If specified, workers in these pools are strictly prevented from processing this job. */
            excluded_pools?: string[];
        };
        /**
         * @description Write-only serializer for layer data nested inside a job submission.
         *
         *     Validates the ``frame_range`` by attempting to parse it via the service
         *     layer before the job is committed to the database.
         *
         *     Attributes:
         *         name: Layer name.
         *         layer_type: Render pass type.
         *         command: Base command template.
         *         frame_range: VFX frame range descriptor.
         *         chunk_size: Frames per chunk.
         *         min_cores: Minimum CPU cores.
         *         min_memory_mb: Minimum RAM in MB.
         *         min_gpus: Minimum GPU count.
         *         tags: Worker compatibility tags.
         *         scene_path: DCC scene file path.
         *         scene_info: DCC scene metadata JSON.
         *         env: Environment variable overrides.
         *         max_retries: Per-frame retry ceiling.
         *         timeout_seconds: Frame execution timeout.
         */
        LayerCreate: {
            name: string;
            /** Render pass type */
            layer_type?: components["schemas"]["LayerTypeEnum"];
            command: string;
            frame_range: string;
            /**
             * Frames per chunk
             * @description Groups this many consecutive frames into a single worker task. High values reduce startup overhead for fast-rendering frames (e.g. comp, playblasts).
             */
            chunk_size?: number;
            /** Minimum CPU cores */
            min_cores?: number;
            /** Minimum memory (MB) */
            min_memory_mb?: number;
            /** Minimum GPUs */
            min_gpus?: number;
            tags?: string[];
            scene_path?: string;
            /** Scene metadata */
            scene_info?: unknown;
            env?: unknown;
            max_retries?: number;
            timeout_seconds?: number | null;
        };
        /**
         * @description Full read-only layer representation for detail views.
         *
         *     Extends :class:`LayerListSerializer` with command, resource, and scene fields.
         *
         *     Attributes:
         *         command: Base command template.
         *         chunk_size: Frames per chunk.
         *         min_cores: Minimum CPU cores.
         *         min_memory_mb: Minimum RAM in MB.
         *         min_gpus: Minimum GPU count.
         *         tags: Worker compatibility tags.
         *         scene_path: DCC scene file path.
         *         scene_info: DCC scene metadata JSON.
         *         env: Environment variable overrides.
         *         max_retries: Per-frame retry ceiling.
         *         timeout_seconds: Frame execution timeout.
         */
        LayerDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Render pass type */
            readonly layer_type: components["schemas"]["LayerTypeEnum"];
            readonly state: components["schemas"]["State1dfEnum"];
            readonly frame_range: string;
            readonly total_frames: number;
            readonly waiting_frames: number;
            readonly ready_frames: number;
            readonly running_frames: number;
            readonly succeeded_frames: number;
            readonly failed_frames: number;
            readonly skipped_frames: number;
            readonly depend_frames: number;
            readonly command: string;
            /**
             * Frames per chunk
             * @description Groups this many consecutive frames into a single worker task. High values reduce startup overhead for fast-rendering frames (e.g. comp, playblasts).
             */
            readonly chunk_size: number;
            /** Minimum CPU cores */
            readonly min_cores: number;
            /** Minimum memory (MB) */
            readonly min_memory_mb: number;
            /** Minimum GPUs */
            readonly min_gpus: number;
            readonly tags: string[];
            readonly scene_path: string;
            /** Scene metadata */
            readonly scene_info: unknown;
            readonly env: unknown;
            readonly max_retries: number;
            readonly timeout_seconds: number | null;
        };
        /**
         * @description Slim read-only layer representation for list views.
         *
         *     Attributes:
         *         id: UUID primary key.
         *         name: Layer name (e.g. 'beauty').
         *         layer_type: Render pass type.
         *         state: Current execution state.
         *         frame_range: VFX frame range descriptor.
         *         total_frames: Counter cache.
         *         waiting_frames: Counter cache.
         *         ready_frames: Counter cache.
         *         running_frames: Counter cache.
         *         succeeded_frames: Counter cache.
         *         failed_frames: Counter cache.
         *         skipped_frames: Counter cache.
         *         depend_frames: Counter cache.
         */
        LayerList: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Render pass type */
            readonly layer_type: components["schemas"]["LayerTypeEnum"];
            readonly state: components["schemas"]["State1dfEnum"];
            readonly frame_range: string;
            readonly total_frames: number;
            readonly waiting_frames: number;
            readonly ready_frames: number;
            readonly running_frames: number;
            readonly succeeded_frames: number;
            readonly failed_frames: number;
            readonly skipped_frames: number;
            readonly depend_frames: number;
        };
        /**
         * @description * `RENDER` - Render
         *     * `UTIL` - Utility
         *     * `POST` - Post
         * @enum {string}
         */
        LayerTypeEnum: "RENDER" | "UTIL" | "POST";
        PaginatedFrameListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["FrameList"][];
        };
        PaginatedJobListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["JobList"][];
        };
        PaginatedLayerListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LayerList"][];
        };
        PaginatedWorkerNodeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkerNode"][];
        };
        PaginatedWorkerPoolList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkerPool"][];
        };
        /**
         * @description Write-only serializer for partial job updates.
         *
         *     Only exposes fields that are safe to mutate post-submission. State
         *     transitions (pause, resume) use dedicated action endpoints instead.
         *
         *     Attributes:
         *         visible_name: Human-readable label.
         *         priority: Dispatch priority (1-100).
         *         max_frames_per_worker: Concurrent frames per Worker limit.
         */
        PatchedJobPatch: {
            visible_name?: string;
            priority?: number;
            /**
             * Max concurrent frames per worker
             * @description Limits how many frames from this job a single machine can run at once. Used to prevent a single job from monopolizing nodes with high core counts.
             */
            max_frames_per_worker?: number;
            /** @description If specified, only workers in these pools can process this job. */
            included_pools?: string[];
            /** @description If specified, workers in these pools are strictly prevented from processing this job. */
            excluded_pools?: string[];
        };
        PatchedWorkerPool: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            description?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `RUNNING` - Running
         *     * `FINISHED` - Finished
         *     * `FAILED` - Failed
         *     * `PAUSED` - Paused
         * @enum {string}
         */
        State1dfEnum: "PENDING" | "RUNNING" | "FINISHED" | "FAILED" | "PAUSED";
        /**
         * @description * `WAITING` - Waiting
         *     * `READY` - Ready
         *     * `RUNNING` - Running
         *     * `CHECKPOINT` - Checkpointing
         *     * `SUCCEEDED` - Succeeded
         *     * `FAILED` - Failed
         *     * `SKIPPED` - Skipped
         * @enum {string}
         */
        State23dEnum: "WAITING" | "READY" | "RUNNING" | "CHECKPOINT" | "SUCCEEDED" | "FAILED" | "SKIPPED";
        /**
         * @description * `ONLINE` - Online
         *     * `OFFLINE` - Offline
         *     * `RENDERING` - Rendering
         * @enum {string}
         */
        StatusEnum: "ONLINE" | "OFFLINE" | "RENDERING";
        WorkerNode: {
            readonly id: number;
            hostname: string;
            ip_address?: string | null;
            status?: components["schemas"]["StatusEnum"];
            readonly pools: components["schemas"]["WorkerPool"][];
            tags?: string[];
            cores?: number;
            memory_mb?: number;
            gpu_models?: string[];
            /** @description Transient and live utilization metrics. */
            system_info?: unknown;
            /** Format: date-time */
            readonly last_ping: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        WorkerPool: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    frames_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `WAITING` - Waiting
                 *     * `READY` - Ready
                 *     * `RUNNING` - Running
                 *     * `CHECKPOINT` - Checkpointing
                 *     * `SUCCEEDED` - Succeeded
                 *     * `FAILED` - Failed
                 *     * `SKIPPED` - Skipped
                 */
                state?: "CHECKPOINT" | "FAILED" | "READY" | "RUNNING" | "SKIPPED" | "SUCCEEDED" | "WAITING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFrameListList"];
                };
            };
        };
    };
    frames_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    frames_checkpoint_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameDetail"];
                "multipart/form-data": components["schemas"]["FrameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    frames_fail_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameFail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameFail"];
                "multipart/form-data": components["schemas"]["FrameFail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameFail"];
                };
            };
        };
    };
    frames_skip_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameDetail"];
                "multipart/form-data": components["schemas"]["FrameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    frames_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameStart"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameStart"];
                "multipart/form-data": components["schemas"]["FrameStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStart"];
                };
            };
        };
    };
    frames_succeed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameSucceed"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameSucceed"];
                "multipart/form-data": components["schemas"]["FrameSucceed"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameSucceed"];
                };
            };
        };
    };
    frames_dispatch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameStart"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameStart"];
                "multipart/form-data": components["schemas"]["FrameStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStart"];
                };
            };
        };
    };
    jobs_list: {
        parameters: {
            query?: {
                department?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                project?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `PENDING` - Pending
                 *     * `RUNNING` - Running
                 *     * `FINISHED` - Finished
                 *     * `FAILED` - Failed
                 *     * `PAUSED` - Paused
                 */
                state?: "FAILED" | "FINISHED" | "PAUSED" | "PENDING" | "RUNNING";
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobListList"];
                };
            };
        };
    };
    jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["JobCreate"];
                "multipart/form-data": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreate"];
                };
            };
        };
    };
    jobs_layers_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                job_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLayerListList"];
                };
            };
        };
    };
    jobs_layers_frames_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `WAITING` - Waiting
                 *     * `READY` - Ready
                 *     * `RUNNING` - Running
                 *     * `CHECKPOINT` - Checkpointing
                 *     * `SUCCEEDED` - Succeeded
                 *     * `FAILED` - Failed
                 *     * `SKIPPED` - Skipped
                 */
                state?: "CHECKPOINT" | "FAILED" | "READY" | "RUNNING" | "SKIPPED" | "SUCCEEDED" | "WAITING";
            };
            header?: never;
            path: {
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFrameListList"];
                };
            };
        };
    };
    jobs_layers_frames_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    jobs_layers_frames_checkpoint_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameDetail"];
                "multipart/form-data": components["schemas"]["FrameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    jobs_layers_frames_fail_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameFail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameFail"];
                "multipart/form-data": components["schemas"]["FrameFail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameFail"];
                };
            };
        };
    };
    jobs_layers_frames_skip_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameDetail"];
                "multipart/form-data": components["schemas"]["FrameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDetail"];
                };
            };
        };
    };
    jobs_layers_frames_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameStart"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameStart"];
                "multipart/form-data": components["schemas"]["FrameStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStart"];
                };
            };
        };
    };
    jobs_layers_frames_succeed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this frame. */
                id: string;
                job_pk: string;
                layer_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FrameSucceed"];
                "application/x-www-form-urlencoded": components["schemas"]["FrameSucceed"];
                "multipart/form-data": components["schemas"]["FrameSucceed"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameSucceed"];
                };
            };
        };
    };
    jobs_layers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                job_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerDetail"];
                };
            };
        };
    };
    jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
        };
    };
    jobs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    jobs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJobPatch"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJobPatch"];
                "multipart/form-data": components["schemas"]["PatchedJobPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPatch"];
                };
            };
        };
    };
    jobs_pause_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["JobDetail"];
                "multipart/form-data": components["schemas"]["JobDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
        };
    };
    jobs_resume_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this job. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["JobDetail"];
                "multipart/form-data": components["schemas"]["JobDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
        };
    };
    pools_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkerPoolList"];
                };
            };
        };
    };
    pools_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerPool"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkerPool"];
                "multipart/form-data": components["schemas"]["WorkerPool"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPool"];
                };
            };
        };
    };
    pools_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this worker pool. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPool"];
                };
            };
        };
    };
    pools_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this worker pool. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerPool"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkerPool"];
                "multipart/form-data": components["schemas"]["WorkerPool"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPool"];
                };
            };
        };
    };
    pools_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this worker pool. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pools_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this worker pool. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkerPool"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorkerPool"];
                "multipart/form-data": components["schemas"]["PatchedWorkerPool"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPool"];
                };
            };
        };
    };
    workers_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkerNodeList"];
                };
            };
        };
    };
    workers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this worker node. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerNode"];
                };
            };
        };
    };
    workers_ping_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerNode"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkerNode"];
                "multipart/form-data": components["schemas"]["WorkerNode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerNode"];
                };
            };
        };
    };
}
