<#
.SYNOPSIS
    RenderHive Server — Post-Installation Configuration Script

.DESCRIPTION
    Called by the Inno Setup installer immediately after all files are
    copied.  Performs every step that requires a running OS or database:

      1.  Write RenderHive.env to the install directory
      2.  Initialise the PostgreSQL data cluster (initdb)
      3.  Register and start PostgreSQL as a Windows service (via NSSM)
      4.  Create the renderhive database and user
      5.  Register and start Redis as a Windows service (via NSSM)
      6.  Run Django migrations
      7.  Create the Django admin superuser
      8.  Run the create_farm_token management command
      9.  Collect Django static files
     10.  Write the nginx.conf (replacing the ROOT placeholder)
     11.  Register nginx as a Windows service (via NSSM)
     12.  Register the Django API as a Windows service (via NSSM)
     13.  Start all services
     14.  Update the system hosts file

.PARAMETER InstallDir
    Absolute path to the installation directory, e.g.
    "C:\Program Files\RenderHive\Server"

.PARAMETER DataDir
    Absolute path to the PostgreSQL data directory, e.g.
    "C:\ProgramData\RenderHive\pgdata"

.PARAMETER ServerIP
    LAN IP address of this server machine, e.g. "192.168.1.100"

.PARAMETER AdminUser
    Django admin username (default: admin)

.PARAMETER AdminPassword
    Django admin password (plain text — stored only in RenderHive.env)

.PARAMETER DbUser
    PostgreSQL username for the RenderHive database (default: renderhive)

.PARAMETER DbPassword
    PostgreSQL password for the RenderHive database

.PARAMETER SecretKey
    Django SECRET_KEY (generated by the Inno Setup wizard)

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File post_install.ps1 `
        -InstallDir "C:\Program Files\RenderHive\Server" `
        -DataDir    "C:\ProgramData\RenderHive\pgdata" `
        -ServerIP   "192.168.1.100" `
        -AdminUser  "admin" `
        -AdminPassword "MyStr0ngPass!" `
        -DbUser     "renderhive" `
        -DbPassword "AnotherStr0ngPass!" `
        -SecretKey  "aRandomly-Generated-50char-String..."
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)][string] $InstallDir,
    [Parameter(Mandatory)][string] $DataDir,
    [Parameter(Mandatory)][string] $ServerIP,
    [string] $AdminUser      = "admin",
    [string] $DbName         = "renderhive",
    [string] $DbUser         = "renderhive",
    [Parameter(Mandatory)][string] $AdminPassword,
    [Parameter(Mandatory)][string] $SecretKey
)

$ErrorActionPreference = "Continue"
$ProgressPreference    = "SilentlyContinue"  # Speed up Invoke-WebRequest

# ---------------------------------------------------------------------------
# Auto-generate database credential (alphanumeric to avoid URL encoding issues)
# ---------------------------------------------------------------------------
$DbPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | % {[char]$_})

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

$ManagerExe  = Join-Path $InstallDir "manager\RenderHiveServer.exe"
$ApiExe      = Join-Path $InstallDir "api\RenderHiveAPI.exe"
$PgBin       = Join-Path $InstallDir "postgres\bin"
$PgInitDb    = Join-Path $PgBin      "initdb.exe"
$PgCtl       = Join-Path $PgBin      "pg_ctl.exe"
$Psql        = Join-Path $PgBin      "psql.exe"
$RedisExe    = Join-Path $InstallDir "redis\redis-server.exe"
$NginxExe    = Join-Path $InstallDir "nginx\nginx.exe"
$NginxRoot   = Join-Path $InstallDir "nginx"
$AiExe       = Join-Path $InstallDir "ai\RenderHiveAI.exe"
$NssmExe     = Join-Path $InstallDir "nssm\nssm.exe"
$FrontendDir = Join-Path $InstallDir "frontend"
$EnvFile     = Join-Path $InstallDir "RenderHive.env"
$LogDir      = Join-Path $InstallDir "logs"

# ---------------------------------------------------------------------------
# Load existing credentials if upgrading
# ---------------------------------------------------------------------------
if (Test-Path $EnvFile) {
    $envLines = Get-Content $EnvFile
    foreach ($line in $envLines) {
        if ($line -match "^DATABASE_URL=postgres://[^:]+:(.+)@127\.0\.0\.1:5432") {
            $DbPassword = $matches[1]
        }
        if ($line -match "^SECRET_KEY=(.*)$") {
            $SecretKey = $matches[1]
        }
    }
}

# Ensure log directory exists
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null

$transcriptLog = Join-Path $LogDir "post_install.log"
try {
    Start-Transcript -Path $transcriptLog -Append -Force -ErrorAction SilentlyContinue
} catch {}

$PgExe       = Join-Path $PgBin      "postgres.exe"

# ---------------------------------------------------------------------------
# Pre-flight: verify all critical binaries exist before proceeding
# ---------------------------------------------------------------------------
$requiredBinaries = @{
    "NSSM"           = $NssmExe
    "PostgreSQL"     = $PgExe
    "initdb"         = $PgInitDb
    "psql"           = $Psql
    "Redis"          = $RedisExe
    "nginx"          = $NginxExe
    "RenderHive API" = $ApiExe
    "AI Service"     = $AiExe
}
foreach ($name in $requiredBinaries.Keys) {
    if (-not (Test-Path $requiredBinaries[$name])) {
        throw "Required binary not found: $name at '$($requiredBinaries[$name])'. Ensure the build completed successfully."
    }
}

function Write-Step([string]$msg) {
    Write-Host ""
    Write-Host "==> $msg" -ForegroundColor Cyan
}

function Write-OK([string]$msg) {
    Write-Host "    OK: $msg" -ForegroundColor Green
}

function Write-Warn([string]$msg) {
    Write-Host "    WARN: $msg" -ForegroundColor Yellow
}

# ---------------------------------------------------------------------------
# Step 1: Write RenderHive.env
# ---------------------------------------------------------------------------

Write-Step "Writing RenderHive.env..."

$DatabaseUrl = "postgres://${DbUser}:${DbPassword}@127.0.0.1:5432/${DbName}"
$AllowedHosts = "${ServerIP},localhost,127.0.0.1,renderhive.local,server.renderhive.local"
$CorsOrigins  = "http://renderhive.local,http://${ServerIP}"
$CsrfOrigins  = "http://renderhive.local,http://${ServerIP}"

$envContent = @"
# RenderHive Server Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# DO NOT EDIT MANUALLY unless you know what you are doing.

SECRET_KEY=${SecretKey}
DEBUG=False

ALLOWED_HOSTS=${AllowedHosts}
CORS_ALLOWED_ORIGINS=${CorsOrigins}
CSRF_TRUSTED_ORIGINS=${CsrfOrigins}

DATABASE_URL=${DatabaseUrl}
REDIS_URL=redis://127.0.0.1:6379/1

DJANGO_SUPERUSER_USERNAME=${AdminUser}
DJANGO_SUPERUSER_EMAIL=${AdminUser}@renderhive.local
DJANGO_SUPERUSER_PASSWORD=${AdminPassword}

RENDERHIVE_INSTALL_DIR=${InstallDir}
API_HOST=127.0.0.1
API_PORT=8000
API_THREADS=4
NEXT_PUBLIC_API_URL=http://server.renderhive.local
"@

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Write-OK "RenderHive.env written to $EnvFile"

# ---------------------------------------------------------------------------
# Step 2: Initialise PostgreSQL data cluster
# ---------------------------------------------------------------------------

Write-Step "Initialising PostgreSQL data cluster..."

$pgDataEmpty = -not (Test-Path (Join-Path $DataDir "PG_VERSION"))

if ($pgDataEmpty) {
    $pgPassword = $DbPassword
    $pgPassFile = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $pgPassFile -Value $pgPassword -Encoding ASCII

    & $PgInitDb `
        --pgdata=$DataDir `
        --username=postgres `
        --pwfile=$pgPassFile `
        --encoding=UTF8 `
        --locale=en-US `
        --auth=md5 2>&1 | Tee-Object -FilePath (Join-Path $LogDir "initdb.log")

    Remove-Item $pgPassFile -Force
    if ($LASTEXITCODE -ne 0) { throw "initdb failed. See $LogDir\initdb.log" }
    Write-OK "PostgreSQL data directory initialised at $DataDir"
} else {
    Write-Warn "PostgreSQL data directory already exists - skipping initdb."
}

# ---------------------------------------------------------------------------
# Step 3: Register and start PostgreSQL service
# ---------------------------------------------------------------------------

Write-Step "Registering PostgreSQL Windows service (RenderHive-Postgres)..."

$svcName = "RenderHive-Postgres"
$pgConf  = Join-Path $DataDir "postgresql.conf"

# Ensure NT AUTHORITY\NetworkService has permissions on data, log, and binary directories
icacls "$DataDir" /grant "NT AUTHORITY\NetworkService:(OI)(CI)F" /T /Q | Out-Null
icacls "$LogDir" /grant "NT AUTHORITY\NetworkService:(OI)(CI)F" /T /Q | Out-Null
icacls (Split-Path $PgBin) /grant "NT AUTHORITY\NetworkService:(OI)(CI)RX" /T /Q | Out-Null

# Append minimal custom settings if not already present
$EscapedLogDir = $LogDir.Replace('\', '\\')
$customSettings = @"

# RenderHive installer additions
listen_addresses = 'localhost'
port = 5432
log_destination = 'stderr'
logging_collector = on
log_directory = '$EscapedLogDir'
log_filename = 'postgres-%Y-%m-%d.log'
log_truncate_on_rotation = on
log_rotation_age = 1d
log_rotation_size = 10MB
"@


if (Test-Path $pgConf) {
    $existing = Get-Content $pgConf -Raw

    if ($existing.Contains("RenderHive installer additions")) {
        # Already patched - but ALWAYS force-update log_directory to the current install path
        # (prevents stale path from a previous installation breaking startup)
        $existing = [regex]::Replace($existing, "(?m)^log_directory\s*=\s*'[^']*'", "log_directory = '$EscapedLogDir'")
        [System.IO.File]::WriteAllText($pgConf, $existing)
        Write-OK "Updated log_directory in postgresql.conf to current install path."
    } else {
        $existing += "`r`n" + $customSettings
        [System.IO.File]::WriteAllText($pgConf, $existing)
        Write-OK "Appended logging settings to postgresql.conf"
    }
}

# Remove service if it already exists (idempotent reinstall)
$existing = sc.exe query $svcName 2>$null
if ($existing -match "SERVICE_NAME") {
    Write-Warn "Service $svcName already exists - removing for clean reinstall..."
    sc.exe stop $svcName 2>$null | Out-Null
    Start-Sleep -Seconds 3
    & $NssmExe remove $svcName confirm 2>&1 | Out-Null
}

& $NssmExe install $svcName $PgExe
& $NssmExe set $svcName AppParameters "-D `"$DataDir`""
& $NssmExe set $svcName AppDirectory  $PgBin
& $NssmExe set $svcName ObjectName    "NT AUTHORITY\NetworkService" ""
& $NssmExe set $svcName DisplayName   "RenderHive PostgreSQL"
& $NssmExe set $svcName Description   "PostgreSQL database server for RenderHive"
& $NssmExe set $svcName Start         SERVICE_AUTO_START
& $NssmExe set $svcName AppStdout     "$LogDir\postgres-stdout.log"
& $NssmExe set $svcName AppStderr     "$LogDir\postgres-stderr.log"

sc.exe start $svcName | Out-Null
Write-Host "    Waiting for PostgreSQL to start..." -NoNewline
$pgReady = $false
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 1
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect("127.0.0.1", 5432)
        if ($tcp.Connected) {
            $tcp.Close()
            $pgReady = $true
            break
        }
    } catch {
        # Keep waiting until port 5432 is open
    }
    Write-Host "." -NoNewline
}
Write-Host ""
if (-not $pgReady) { throw "PostgreSQL failed to start within 30 seconds. Check $LogDir\postgres-stderr.log" }
Write-OK "PostgreSQL service started."

# ---------------------------------------------------------------------------
# Step 4: Create the RenderHive database and user
# ---------------------------------------------------------------------------

Write-Step "Creating RenderHive database and user..."

$env:PGPASSWORD = $DbPassword

$createUserSql = "DO `$`$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DbUser') THEN CREATE ROLE $DbUser LOGIN PASSWORD '$DbPassword'; END IF; END `$`$;"
$checkDbSql    = "SELECT 1 FROM pg_database WHERE datname = '$DbName';"
$createDbSql   = "CREATE DATABASE $DbName OWNER $DbUser;"

& $Psql -h 127.0.0.1 -U postgres -c $createUserSql
$dbExists = & $Psql -h 127.0.0.1 -U postgres -tAc $checkDbSql
if ($dbExists -match "1") {
    Write-Warn "Database '$DbName' already exists - skipping CREATE DATABASE."
} else {
    & $Psql -h 127.0.0.1 -U postgres -c $createDbSql
    Write-OK "Database '$DbName' created."
}

Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
Write-OK "Database '$DbName' and user '$DbUser' ready."

# ---------------------------------------------------------------------------
# Step 5: Register and start Redis service
# ---------------------------------------------------------------------------

Write-Step "Registering Redis Windows service (RenderHive-Redis)..."

$redisSvcName = "RenderHive-Redis"
$redisConf    = Join-Path $InstallDir "redis\redis.conf"

$redisLogPath = (Join-Path $LogDir "redis.log").Replace("\", "/")
# Write a minimal redis.conf
$redisConfContent = @"
bind 127.0.0.1
port 6379
loglevel notice
logfile `"$redisLogPath`"
maxmemory 256mb
maxmemory-policy allkeys-lru
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($redisConf, $redisConfContent, $utf8NoBom)

$existingRedis = sc.exe query $redisSvcName 2>$null
if ($existingRedis -match "SERVICE_NAME") {
    sc.exe stop $redisSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $redisSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $redisSvcName $RedisExe
& $NssmExe set $redisSvcName AppDirectory   (Split-Path $RedisExe)
& $NssmExe set $redisSvcName AppParameters  "redis.conf"

& $NssmExe set $redisSvcName DisplayName    "RenderHive Redis"
& $NssmExe set $redisSvcName Description    "Redis cache server for RenderHive"
& $NssmExe set $redisSvcName Start          SERVICE_AUTO_START
& $NssmExe set $redisSvcName AppStdout      "$LogDir\redis-stdout.log"
& $NssmExe set $redisSvcName AppStderr      "$LogDir\redis-stderr.log"

sc.exe start $redisSvcName | Out-Null
Start-Sleep -Seconds 2
Write-OK "Redis service started."

# ---------------------------------------------------------------------------
# Step 6: Run Django migrations
# ---------------------------------------------------------------------------

Write-Step "Running Django migrations..."
& $ApiExe --migrate 2>&1 | Tee-Object -FilePath (Join-Path $LogDir "setup-migrate.log")
if ($LASTEXITCODE -ne 0) { throw "Django migrations failed (exit code $LASTEXITCODE). Binary: '$ApiExe'. See $LogDir\setup-migrate.log" }
Write-OK "Migrations complete."

# ---------------------------------------------------------------------------
# Step 7: Create Django admin superuser
# ---------------------------------------------------------------------------

Write-Step "Creating Django admin superuser..."
$env:DJANGO_SUPERUSER_USERNAME = $AdminUser
$env:DJANGO_SUPERUSER_EMAIL    = "$AdminUser@renderhive.local"
$env:DJANGO_SUPERUSER_PASSWORD = $AdminPassword
& $ApiExe --create-superuser 2>&1 | Tee-Object -FilePath (Join-Path $LogDir "setup-superuser.log")
Remove-Item Env:\DJANGO_SUPERUSER_USERNAME, Env:\DJANGO_SUPERUSER_EMAIL, Env:\DJANGO_SUPERUSER_PASSWORD -ErrorAction SilentlyContinue
Write-OK "Admin superuser ready."

# ---------------------------------------------------------------------------
# Step 8: Create farm service token
# ---------------------------------------------------------------------------

Write-Step "Creating farm service token..."
& $ApiExe --farm-token 2>&1 | Tee-Object -FilePath (Join-Path $LogDir "setup-farmtoken.log")
Write-OK "Farm token created. Check farm_token.txt in the install directory."

# ---------------------------------------------------------------------------
# Step 9: Collect Django static files
# ---------------------------------------------------------------------------

Write-Step "Collecting static files..."
& $ApiExe --collect-static 2>&1 | Tee-Object -FilePath (Join-Path $LogDir "setup-collectstatic.log")
Write-OK "Static files collected."

# ---------------------------------------------------------------------------
# Step 10: Write nginx.conf (resolve the RENDERHIVE_FRONTEND_ROOT placeholder)
# ---------------------------------------------------------------------------

Write-Step "Configuring nginx..."

$nginxConfTemplate = Join-Path $NginxRoot "conf\nginx.conf.template"
$nginxConf         = Join-Path $NginxRoot "conf\nginx.conf"

if (Test-Path $nginxConfTemplate) {
    $nginxContent = Get-Content $nginxConfTemplate -Raw
    $nginxContent = $nginxContent.Replace("RENDERHIVE_FRONTEND_ROOT", $FrontendDir.Replace("\", "/"))
    $nginxContent = $nginxContent.Replace("RENDERHIVE_INSTALL_DIR", $InstallDir.Replace("\", "/"))
    
    # Write UTF-8 without BOM so nginx doesn't choke on '<_' at line 1
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($nginxConf, $nginxContent, $utf8NoBom)
    
    Remove-Item $nginxConfTemplate
    Write-OK "nginx.conf written (no BOM)."
} else {
    Write-Warn "nginx.conf.template not found - skipping."
}

# ---------------------------------------------------------------------------
# Step 11: Register nginx service
# ---------------------------------------------------------------------------

Write-Step "Registering nginx Windows service (RenderHive-Nginx)..."

$nginxSvcName = "RenderHive-Nginx"
$existingNginx = sc.exe query $nginxSvcName 2>$null
if ($existingNginx -match "SERVICE_NAME") {
    sc.exe stop $nginxSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $nginxSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $nginxSvcName $NginxExe
& $NssmExe set $nginxSvcName AppDirectory  $NginxRoot
& $NssmExe set $nginxSvcName DisplayName   "RenderHive nginx"
& $NssmExe set $nginxSvcName Description   "nginx reverse proxy for RenderHive"
& $NssmExe set $nginxSvcName Start         SERVICE_AUTO_START
& $NssmExe set $nginxSvcName AppStdout     "$LogDir\nginx-stdout.log"
& $NssmExe set $nginxSvcName AppStderr     "$LogDir\nginx-error.log"
Write-OK "nginx service registered."

# ---------------------------------------------------------------------------
# Step 12: Register Django API service
# ---------------------------------------------------------------------------

Write-Step "Registering Django API Windows service (RenderHive-API)..."

$apiSvcName = "RenderHive-API"
$existingApi = sc.exe query $apiSvcName 2>$null
if ($existingApi -match "SERVICE_NAME") {
    sc.exe stop $apiSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $apiSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $apiSvcName $ApiExe
& $NssmExe set $apiSvcName AppDirectory  (Split-Path $ApiExe)
& $NssmExe set $apiSvcName DisplayName   "RenderHive API"
& $NssmExe set $apiSvcName Description   "Django/waitress REST API for RenderHive"
& $NssmExe set $apiSvcName Start         SERVICE_AUTO_START
& $NssmExe set $apiSvcName AppStdout     "$LogDir\api.log"
& $NssmExe set $apiSvcName AppStderr     "$LogDir\api-error.log"
Write-OK "API service registered."

# ---------------------------------------------------------------------------
# Step 12.1: Register Celery Worker service
# ---------------------------------------------------------------------------

Write-Step "Registering Celery Worker Windows service (RenderHive-Celery-Worker)..."

$celeryWorkerSvcName = "RenderHive-Celery-Worker"
$existingWorker = sc.exe query $celeryWorkerSvcName 2>$null
if ($existingWorker -match "SERVICE_NAME") {
    sc.exe stop $celeryWorkerSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $celeryWorkerSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $celeryWorkerSvcName $ApiExe "--celery-worker"
& $NssmExe set $celeryWorkerSvcName AppDirectory  (Split-Path $ApiExe)
& $NssmExe set $celeryWorkerSvcName DisplayName   "RenderHive Celery Worker"
& $NssmExe set $celeryWorkerSvcName Description   "Celery background task worker for RenderHive"
& $NssmExe set $celeryWorkerSvcName Start         SERVICE_AUTO_START
& $NssmExe set $celeryWorkerSvcName AppStdout     "$LogDir\celery-worker.log"
& $NssmExe set $celeryWorkerSvcName AppStderr     "$LogDir\celery-worker-error.log"
Write-OK "Celery Worker service registered."

# ---------------------------------------------------------------------------
# Step 12.2: Register Celery Beat service
# ---------------------------------------------------------------------------

Write-Step "Registering Celery Beat Windows service (RenderHive-Celery-Beat)..."

$celeryBeatSvcName = "RenderHive-Celery-Beat"
$existingBeat = sc.exe query $celeryBeatSvcName 2>$null
if ($existingBeat -match "SERVICE_NAME") {
    sc.exe stop $celeryBeatSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $celeryBeatSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $celeryBeatSvcName $ApiExe "--celery-beat"
& $NssmExe set $celeryBeatSvcName AppDirectory  (Split-Path $ApiExe)
& $NssmExe set $celeryBeatSvcName DisplayName   "RenderHive Celery Beat"
& $NssmExe set $celeryBeatSvcName Description   "Celery periodic task scheduler for RenderHive"
& $NssmExe set $celeryBeatSvcName Start         SERVICE_AUTO_START
& $NssmExe set $celeryBeatSvcName AppStdout     "$LogDir\celery-beat.log"
& $NssmExe set $celeryBeatSvcName AppStderr     "$LogDir\celery-beat-error.log"
Write-OK "Celery Beat service registered."

# ---------------------------------------------------------------------------
# Step 12.5: Register AI Service
# ---------------------------------------------------------------------------

Write-Step "Registering AI Windows service (RenderHive-AI)..."

$aiSvcName = "RenderHive-AI"
$existingAi = sc.exe query $aiSvcName 2>$null
if ($existingAi -match "SERVICE_NAME") {
    sc.exe stop $aiSvcName 2>$null | Out-Null
    Start-Sleep -Seconds 2
    & $NssmExe remove $aiSvcName confirm 2>&1 | Out-Null
}

& $NssmExe install $aiSvcName $AiExe
& $NssmExe set $aiSvcName AppDirectory  (Split-Path $AiExe)
& $NssmExe set $aiSvcName DisplayName   "RenderHive AI Service"
& $NssmExe set $aiSvcName Description   "FastAPI AI Service for RenderHive"
& $NssmExe set $aiSvcName Start         SERVICE_AUTO_START
& $NssmExe set $aiSvcName AppStdout     "$LogDir\ai-stdout.log"
& $NssmExe set $aiSvcName AppStderr     "$LogDir\ai-error.log"
Write-OK "AI service registered."

# ---------------------------------------------------------------------------
# Step 13: Start all services
# ---------------------------------------------------------------------------

Write-Step "Starting all services..."
sc.exe start $apiSvcName          | Out-Null
sc.exe start $celeryWorkerSvcName | Out-Null
sc.exe start $celeryBeatSvcName   | Out-Null
sc.exe start $aiSvcName           | Out-Null
sc.exe start $nginxSvcName        | Out-Null
Start-Sleep -Seconds 3
Write-OK "All services started."

# ---------------------------------------------------------------------------
# Step 14: Update the hosts file
# ---------------------------------------------------------------------------

Write-Step "Updating hosts file..."

$hostsPath = "$env:windir\System32\drivers\etc\hosts"
$hostsContent = Get-Content $hostsPath -Raw

$entries = @(
    "127.0.0.1 renderhive.local",
    "127.0.0.1 server.renderhive.local"
)

foreach ($entry in $entries) {
    $domain = ($entry -split " ")[1]
    if ($hostsContent -match [regex]::Escape($domain)) {
        # Update existing entry
        $hostsContent = [regex]::Replace(
            $hostsContent,
            "(?m)^[^\s#]+\s+$([regex]::Escape($domain))\s*$",
            $entry
        )
    } else {
        # Append new entry
        $hostsContent += "`n$entry"
    }
}

Set-Content -Path $hostsPath -Value $hostsContent -Encoding ASCII
Write-OK "Hosts file updated."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  RenderHive Server installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Dashboard:  http://renderhive.local" -ForegroundColor White
Write-Host "  Admin:      http://renderhive.local/admin/" -ForegroundColor White
Write-Host "  API:        http://server.renderhive.local/api/" -ForegroundColor White
Write-Host ""
Write-Host "  Admin user:     $AdminUser" -ForegroundColor White
Write-Host "  Farm token:     See $InstallDir\farm_token.txt" -ForegroundColor White
Write-Host "============================================================" -ForegroundColor Green

try {
    Stop-Transcript -ErrorAction SilentlyContinue
} catch {}
