# Generated by Django 5.2.16 on 2026-07-13 14:17

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('visible_name', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(db_index=True, max_length=64)),
                ('department', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user', models.CharField(db_index=True, help_text="The submitter's display name. Defaults to the OS username in the DCC plugin but is manually editable. Matches Deadline's UserName field.", max_length=64)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=16)),
                ('is_paused', models.BooleanField(default=False)),
                ('priority', models.IntegerField(db_index=True, default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_frames_per_worker', models.PositiveIntegerField(default=1, verbose_name='max concurrent frames per worker')),
                ('log_directory', models.CharField(max_length=2048)),
                ('total_frames', models.IntegerField(default=0)),
                ('waiting_frames', models.IntegerField(default=0)),
                ('ready_frames', models.IntegerField(default=0)),
                ('running_frames', models.IntegerField(default=0)),
                ('succeeded_frames', models.IntegerField(default=0)),
                ('failed_frames', models.IntegerField(default=0)),
                ('skipped_frames', models.IntegerField(default=0)),
                ('depend_frames', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Populated ONLY when submitted via the web frontend. NULL for DCC plugin submissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('layer_type', models.CharField(choices=[('RENDER', 'Render'), ('UTIL', 'Utility'), ('POST', 'Post')], default='RENDER', max_length=8, verbose_name='render pass type')),
                ('command', models.TextField()),
                ('frame_range', models.CharField(max_length=1024)),
                ('chunk_size', models.PositiveIntegerField(default=1, verbose_name='frames per chunk')),
                ('min_cores', models.PositiveIntegerField(default=1, verbose_name='minimum CPU cores')),
                ('min_memory_mb', models.PositiveIntegerField(default=4096, verbose_name='minimum memory (MB)')),
                ('min_gpus', models.PositiveIntegerField(default=0, verbose_name='minimum GPUs')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('scene_path', models.CharField(blank=True, max_length=2048)),
                ('scene_info', models.JSONField(blank=True, default=dict, verbose_name='scene metadata')),
                ('env', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=16)),
                ('total_frames', models.IntegerField(default=0)),
                ('waiting_frames', models.IntegerField(default=0)),
                ('ready_frames', models.IntegerField(default=0)),
                ('running_frames', models.IntegerField(default=0)),
                ('succeeded_frames', models.IntegerField(default=0)),
                ('failed_frames', models.IntegerField(default=0)),
                ('skipped_frames', models.IntegerField(default=0)),
                ('depend_frames', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='jobs.job')),
            ],
            options={
                'verbose_name': 'layer',
                'verbose_name_plural': 'layers',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField(db_index=True)),
                ('dispatch_order', models.IntegerField(db_index=True, default=0)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('CHECKPOINT', 'Checkpointing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='WAITING', max_length=16)),
                ('depend_count', models.IntegerField(db_index=True, default=0, verbose_name='dependency count')),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('checkpoint_count', models.PositiveIntegerField(default=0)),
                ('exit_status', models.IntegerField(default=-1)),
                ('max_memory_used_mb', models.PositiveIntegerField(default=0, verbose_name='peak memory used (MB)')),
                ('cores_used', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='worker hostname')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='jobs.job')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='jobs.layer')),
            ],
            options={
                'verbose_name': 'frame',
                'verbose_name_plural': 'frames',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('JOB_ON_JOB', 'Job on Job'), ('LAYER_ON_LAYER', 'Layer on Layer'), ('FRAME_ON_FRAME', 'Frame on Frame')], db_index=True, max_length=24)),
                ('is_satisfied', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('dep_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dependencies', to='jobs.frame')),
                ('parent_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='jobs.frame')),
                ('dep_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dependencies', to='jobs.job')),
                ('parent_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='jobs.job')),
                ('dep_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dependencies', to='jobs.layer')),
                ('parent_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='jobs.layer')),
            ],
            options={
                'verbose_name': 'dependency',
                'verbose_name_plural': 'dependencies',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'priority'], name='jobs_job_state_58a14f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['project', 'state'], name='jobs_job_project_58e9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'state'], name='jobs_job_user_1eee2f_idx'),
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['job', 'state'], name='jobs_layer_job_id_8f7c33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('job', 'name')},
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['job', 'state'], name='jobs_frame_job_id_4c7423_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['layer', 'state'], name='jobs_frame_layer_i_196d45_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['state', 'depend_count'], name='jobs_frame_state_3ab672_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('layer', 'number')},
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['parent_frame', 'is_satisfied'], name='jobs_depend_parent__3446af_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['parent_layer', 'is_satisfied'], name='jobs_depend_parent__3dfa93_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['parent_job', 'is_satisfied'], name='jobs_depend_parent__65b975_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['dep_frame', 'is_satisfied'], name='jobs_depend_dep_fra_6afc58_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['dep_layer', 'is_satisfied'], name='jobs_depend_dep_lay_64aaa3_idx'),
        ),
    ]
