# Generated by Django 5.2.16 on 2026-07-26 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_excluded_pools_job_included_pools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('frame_start', models.IntegerField(db_index=True)),
                ('frame_end', models.IntegerField(db_index=True)),
                ('dispatch_order', models.IntegerField(db_index=True, default=0, help_text='Scheduler priority within the layer. Lower numbers are dispatched first.')),
                ('state', models.CharField(choices=[('WAITING', 'Waiting'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('CHECKPOINT', 'Checkpointing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='WAITING', max_length=16)),
                ('depend_count', models.IntegerField(db_index=True, default=0, verbose_name='dependency count')),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('checkpoint_count', models.PositiveIntegerField(default=0, help_text='How many times the worker has reported saving intermediate progress (useful for resuming aborted tasks).')),
                ('exit_status', models.IntegerField(default=-1, help_text='Raw process exit code returned by the worker. -1 means the task has not completed.')),
                ('max_memory_used_mb', models.PositiveIntegerField(default=0, verbose_name='peak memory used (MB)')),
                ('cores_used', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='worker hostname')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='frame',
            name='job',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='parent_frame',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='dep_frame',
        ),
        migrations.RemoveIndex(
            model_name='dependency',
            name='jobs_depend_parent__3446af_idx',
        ),
        migrations.RemoveIndex(
            model_name='dependency',
            name='jobs_depend_dep_fra_6afc58_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='depend_frames',
            new_name='depend_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='failed_frames',
            new_name='failed_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ready_frames',
            new_name='ready_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='running_frames',
            new_name='running_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skipped_frames',
            new_name='skipped_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='succeeded_frames',
            new_name='succeeded_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='total_frames',
            new_name='total_tasks',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='waiting_frames',
            new_name='waiting_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='depend_frames',
            new_name='depend_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='failed_frames',
            new_name='failed_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='ready_frames',
            new_name='ready_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='running_frames',
            new_name='running_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='skipped_frames',
            new_name='skipped_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='succeeded_frames',
            new_name='succeeded_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='total_frames',
            new_name='total_tasks',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='waiting_frames',
            new_name='waiting_tasks',
        ),
        migrations.AlterField(
            model_name='dependency',
            name='type',
            field=models.CharField(choices=[('JOB_ON_JOB', 'Job on Job'), ('LAYER_ON_LAYER', 'Layer on Layer'), ('TASK_ON_TASK', 'Task on Task')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.layer'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dep_task',
            field=models.ForeignKey(blank=True, help_text='The specific task that is WAITING (required for TASK_ON_TASK dependencies).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dependencies', to='jobs.task', verbose_name='blocked task'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='The specific task that must complete FIRST (required for TASK_ON_TASK dependencies).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='jobs.task', verbose_name='blocking task'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['parent_task', 'is_satisfied'], name='jobs_depend_parent__d21ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='dependency',
            index=models.Index(fields=['dep_task', 'is_satisfied'], name='jobs_depend_dep_tas_e71765_idx'),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['job', 'state'], name='jobs_task_job_id_49f699_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['layer', 'state'], name='jobs_task_layer_i_c149e6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state', 'depend_count'], name='jobs_task_state_6907f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('layer', 'frame_start', 'frame_end')},
        ),
    ]
