# Generated by Django 5.2.16 on 2026-07-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_task_alter_frame_unique_together_remove_frame_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='max_frames_per_worker',
        ),
        migrations.AddField(
            model_name='job',
            name='max_tasks_per_worker',
            field=models.PositiveIntegerField(default=1, help_text='Limits how many tasks from this job a single machine can run at once. Used to prevent a single job from monopolizing nodes with high core counts.', verbose_name='max concurrent tasks per worker'),
        ),
    ]
