# Generated by Django 5.2.16 on 2026-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_max_frames_per_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_score_breakdown',
            field=models.JSONField(blank=True, help_text='Observability field containing the breakdown of the dispatch score and AI adjustments.', null=True),
        ),
    ]
