# Generated by Django 5.2.17 on 2026-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_task_last_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, verbose_name='output file size in bytes'),
        ),
        migrations.AddField(
            model_name='task',
            name='peak_cpu_percent',
            field=models.FloatField(default=0.0, verbose_name='peak CPU percent'),
        ),
    ]
