import uuid

from django.db import models


class EventSeverity(models.TextChoices):
    INFO = "INFO", "Info"
    WARNING = "WARNING", "Warning"
    ERROR = "ERROR", "Error"
    CRITICAL = "CRITICAL", "Critical"


class TaskExecutionLog(models.Model):
    """Execution output, diagnostics, and metrics for a specific task attempt.

    Attributes:
        id: UUID primary key.
        task: FK to the Task entity.
        job: Denormalized FK to Job for fast cascade deletes and job-level log queries.
        attempt_number: The 1-indexed retry/attempt counter for this execution.
        worker_hostname: The worker machine that executed the task.
        exit_status: Process exit code (0 for success, non-zero for failure).
        duration_seconds: Task execution wall clock time in seconds.
        peak_memory_mb: Peak RSS memory reported by the worker in MB.
        output_image_path: Absolute or network path to the rendered output image file.
        error_tail: The last 20-50 lines of log output extracted on failure.
        log_output: Full standard output and standard error text (Postgres TOAST compressed).
        created_at: Timestamp when the log was submitted.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task = models.ForeignKey(
        "jobs.Task",
        on_delete=models.CASCADE,
        related_name="execution_logs",
        help_text="The task this log belongs to.",
    )
    job = models.ForeignKey(
        "jobs.Job",
        on_delete=models.CASCADE,
        related_name="telemetry_logs",
        help_text="Denormalized Job foreign key for fast cascading and filtering.",
    )
    attempt_number = models.PositiveIntegerField(default=1)
    worker_hostname = models.CharField(max_length=255, db_index=True)

    exit_status = models.IntegerField(default=0)
    duration_seconds = models.FloatField(default=0.0)
    peak_memory_mb = models.PositiveIntegerField(default=0)
    peak_cpu_percent = models.FloatField(default=0.0)
    file_size_bytes = models.BigIntegerField(default=0)
    output_image_path = models.CharField(max_length=2048, blank=True)

    error_tail = models.TextField(blank=True, help_text="Fast-access failure excerpt.")
    log_output = models.TextField(blank=True, help_text="Full stdout/stderr text, TOAST-compressed.")
    ai_explanation = models.TextField(blank=True, help_text="Pre-computed AI explanation of the error.")
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = "task execution log"
        verbose_name_plural = "task execution logs"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["task", "-attempt_number"]),
            models.Index(fields=["job", "-created_at"]),
            models.Index(fields=["worker_hostname", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.task.name} [attempt #{self.attempt_number}] on {self.worker_hostname} (exit {self.exit_status})"


class DispatchTrace(models.Model):
    """Historical trace of a scheduler dispatch evaluation, scoring breakdown, and AI decision.

    Attributes:
        id: UUID primary key.
        task: FK to Task (nullable if task is deleted).
        job: FK to parent Job.
        worker_hostname: The worker that requested and claimed the task.
        candidate_count: Number of eligible candidate tasks evaluated during this dispatch cycle.
        ai_invoked: Whether the AI tie-breaker model was called.
        ai_latency_ms: Response time of the AI scheduler service in milliseconds.
        ai_reason: Human-readable rationale generated by the AI tie-breaker.
        score_breakdown: Full scoring breakdown dict from BaseScorer + AI adjustments.
        dispatched_at: Timestamp when dispatch occurred.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task = models.ForeignKey(
        "jobs.Task",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="dispatch_traces",
    )
    job = models.ForeignKey(
        "jobs.Job",
        on_delete=models.CASCADE,
        related_name="dispatch_traces",
    )
    worker_hostname = models.CharField(max_length=255, db_index=True)

    candidate_count = models.IntegerField(default=1)
    ai_invoked = models.BooleanField(default=False, db_index=True)
    ai_latency_ms = models.FloatField(null=True, blank=True)
    ai_reason = models.TextField(blank=True)
    score_breakdown = models.JSONField(default=dict, blank=True)
    dispatched_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = "dispatch trace"
        verbose_name_plural = "dispatch traces"
        ordering = ["-dispatched_at"]
        indexes = [
            models.Index(fields=["job", "-dispatched_at"]),
            models.Index(fields=["worker_hostname", "-dispatched_at"]),
            models.Index(fields=["ai_invoked", "-dispatched_at"]),
        ]

    def __str__(self):
        task_label = self.task.name if self.task else "Deleted Task"
        return f"Dispatch {task_label} -> {self.worker_hostname} (AI: {self.ai_invoked})"


class FarmEvent(models.Model):
    """Audit log entry capturing administrative and lifecycle actions across the render farm.

    Attributes:
        id: UUID primary key.
        event_type: Categorical identifier (e.g. 'JOB_PAUSED', 'TASK_SKIPPED', 'WORKER_OFFLINE').
        severity: INFO, WARNING, ERROR, or CRITICAL.
        actor_username: Display name or username of the user who initiated the action, or 'system'.
        target_type: 'job', 'task', 'worker', 'pool', or 'system'.
        target_id: Stable identifier or UUID of the target entity.
        message: Human-readable summary of the event.
        payload: Additional structured contextual data.
        created_at: Event timestamp.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event_type = models.CharField(max_length=64, db_index=True)
    severity = models.CharField(max_length=16, choices=EventSeverity.choices, default=EventSeverity.INFO, db_index=True)
    actor_username = models.CharField(max_length=64, blank=True, db_index=True)

    target_type = models.CharField(max_length=32, db_index=True, blank=True)
    target_id = models.CharField(max_length=64, db_index=True, blank=True)
    target_name = models.CharField(max_length=128, blank=True, default="", db_index=True)

    message = models.CharField(max_length=512)
    payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = "farm event"
        verbose_name_plural = "farm events"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["event_type", "-created_at"]),
            models.Index(fields=["target_type", "target_id", "-created_at"]),
            models.Index(fields=["severity", "-created_at"]),
        ]

    def __str__(self):
        return f"[{self.severity}] {self.event_type}: {self.message}"


class WorkerMetricSnapshot(models.Model):
    """Historical time-series sample of worker node hardware utilization.

    Attributes:
        id: UUID primary key.
        worker_hostname: The worker hostname reporting metrics.
        cpu_percent: CPU utilization percentage (0-100).
        memory_used_mb: Active memory in megabytes.
        memory_total_mb: Total capacity memory in megabytes.
        vram_percent: GPU VRAM utilization percentage (0-100).
        active_tasks: Number of tasks running on this worker when sample was captured.
        recorded_at: Timestamp when sample was recorded.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    worker_hostname = models.CharField(max_length=255, db_index=True)
    cpu_percent = models.FloatField(default=0.0)
    memory_used_mb = models.PositiveIntegerField(default=0)
    memory_total_mb = models.PositiveIntegerField(default=4096)
    vram_percent = models.FloatField(default=0.0)
    active_tasks = models.IntegerField(default=0)
    recorded_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = "worker metric snapshot"
        verbose_name_plural = "worker metric snapshots"
        ordering = ["-recorded_at"]
        indexes = [
            models.Index(fields=["worker_hostname", "-recorded_at"]),
            models.Index(fields=["-recorded_at"]),
        ]

    def __str__(self):
        return (
            f"{self.worker_hostname} @ {self.recorded_at.isoformat()} "
            f"(CPU: {self.cpu_percent}%, VRAM: {self.vram_percent}%)"
        )

